### ISSUE TITLE
A version tag would be great for vendoring purposes

### ISSUE THREAD

**Issue by tandr** [akutz/sortfold#1]
Would it be possible to get v1.0 (or whatever you seem fit) version tag?

Thank you very much,
  Andrey

**Comment by akutz** [comment]
What, like [this one](https://github.com/akutz/sortfold/releases/tag/v0.1.0)? :) Thank you for the feedback!

p.s. Yes, I did just create that :)

**Comment by tandr** [comment]
That will work 👍
